CREATE TABLE IF NOT EXISTS MINI_LEAGUE_SCORES (
    LEAGUE_ID      INT  NOT NULL,
    PLAYER_ID      INT  NOT NULL,
    ROUND          INT  NOT NULL,
    SEASON         INT  NOT NULL,
    BASIC_POINTS   INT,
    H2H_POINTS     INT,
    DERBY_POINTS   INT,
    DMM_POINTS     INT,
    LONELY_POINTS  INT,
    SUBTOTAL       INT,
    TOTAL          INT,
    DOCKED_POINTS  INT,
    RUNNING_TOTAL  INT,
    PRIMARY KEY (LEAGUE_ID, PLAYER_ID, ROUND, SEASON),
    INDEX idx_league_season (LEAGUE_ID, SEASON)
);
