CREATE TABLE IF NOT EXISTS MINI_LEAGUE_MEMBERS (
    LEAGUE_ID   INT          NOT NULL,
    PLAYER_ID   INT          NOT NULL,
    ROLE        VARCHAR(20)  DEFAULT 'member',
    JOINED_AT   DATETIME     DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (LEAGUE_ID, PLAYER_ID),
    INDEX idx_player (PLAYER_ID)
);
