CREATE TABLE IF NOT EXISTS MINI_LEAGUES (
    LEAGUE_ID   INT           NOT NULL AUTO_INCREMENT,
    LEAGUE_NAME VARCHAR(100)  NOT NULL,
    CREATED_BY  INT           NOT NULL,
    SEASON      INT           NOT NULL,
    INVITE_CODE VARCHAR(6)    NOT NULL,
    CREATED_AT  DATETIME      DEFAULT CURRENT_TIMESTAMP,
    ICON        VARCHAR(50)   NOT NULL DEFAULT 'shield-outline',
    ICON_BG     VARCHAR(10)   NOT NULL DEFAULT '#1a2a3a',
    ICON_COLOR  VARCHAR(10)   NOT NULL DEFAULT '#7ab8c4',
    PRIMARY KEY (LEAGUE_ID),
    UNIQUE (INVITE_CODE),
    INDEX idx_season (SEASON),
    INDEX idx_created_by (CREATED_BY)
);
