CREATE TABLE IF NOT EXISTS USERS (
    PLAYER_ID           INT,
    EMAIL               VARCHAR(100),
    FULL_NAME           VARCHAR(100),
    USERNAME            VARCHAR(100),
    FAV_TEAM            VARCHAR(100),
    CREATED_AT          TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
    HASHED_PASSWORD     VARCHAR(255), 
    IS_DISABLED         BOOLEAN DEFAULT FALSE
);