UPDATE USERS SET USERNAME = TRIM(USERNAME) WHERE USERNAME IS NOT NULL;

-- Convert empty strings to NULL — UNIQUE indexes allow multiple NULLs in MariaDB
UPDATE USERS SET USERNAME = NULL WHERE USERNAME = '' OR USERNAME IS NULL;

ALTER TABLE USERS
  ADD UNIQUE INDEX uq_users_username (USERNAME);