ALTER TABLE CALL_LOGS
    ADD COLUMN IF NOT EXISTS PLATFORM VARCHAR(20) NULL AFTER ENDPOINT,
    ADD COLUMN IF NOT EXISTS STATUS_CODE INT NULL AFTER PLATFORM,
    ADD COLUMN IF NOT EXISTS DURATION_MS DECIMAL(8, 2) NULL AFTER STATUS_CODE;
